### ISSUE TITLE
only labels of validation-failing radio buttons and checkboxes receive error class

### ISSUE THREAD

**Issue by stefanguha** [LaxarJS/ax-input-control#12]
in `toggleErrorClass` function there is special treatment for radio buttons and checkboxes that fail form validation.

Instead of attributing the error style to the controls themselves, only their labels are decorated with `ax-error` class.
For maximum flexibility in styling laxar applications, also the input controls themselves should carry the error class, imho.

**Comment by x1B** [comment]
I think this is a totally valid point, thanks for the report.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
