### ISSUE TITLE
Validation message shouldn't be affected by title attribute

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/ax-input-control#16]
The input control uses the value of the title attribute as validation message for the tooltip. It should use the message given by the semantic validator.

**Comment by x1B** [comment]
Just to clarify: in general, the correct validation message is used. But whenever the user specifies a `title` attribute, the validation message is overridden by that title.

**Comment by x1B** [comment]
Fixed on `master` (`v2.0.0`), `master-1.x` (`v1.3.x`) and `release-1.2.x` (`v1.2.2`).
