### ISSUE TITLE
Add validation-reset mechanism

### ISSUE THREAD

**Issue by muhkuhxy** [LaxarJS/ax-input-control#23]
For example when validation happens in a modal dialog or popup, the error messages and markers should not persist when the popup is closed and reopened. To achieve this, you could provide an event that resets all css classes etc.

**Comment by x1B** [comment]
@muhkuhxy Good idea, should be relatively simple to implement. It should already be possible to achieve the desired effect by calling `$setPristine()` on an `ngFromController` up the scope chain (or directly on the associated `ngModelController`).
But for consistency with `axInput.validate` we should add a new event `axInput.setPristine` anyway, which is also safer when the form controller has not been instantiated yet.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
