### ISSUE TITLE
Update to Laxar 2, Angular 1.6 and Jasmine 2

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/ax-input-control#29]
A lot to do here.

The obvious:
- [x] fix the widget to use new APIs (Laxar, Angular)
- [x] update the tests to use new Jasmine APIs

Non-Obvious:
- [x] update to webpack
- [x] add package.json, pull dependencies via npm
- [x] add packaging step
- [x] add travis stuff
- [x] remove dependency on laxar-compatibility
- [x] (new!) update use of axI18n

Optional:
- [x] rename all references to laxar-input-control (incl. repo)
- [x] create a new module where common snippets for webpack and karma configuration can be bundled, so we don't have to paste it into each and every artifact
- [x] remove bower.json, require_config.js?

**Comment by x1B** [comment]
@jpommerening WRT to the last item: yes, let's remove bower/require-infrastructure for all artifacts that rely on LaxarJS v2+. We won't be able to maintain them, and their existence gives the impression that they are working/supported.

(edit: @jonaswjs sorry for the mis-mention)

**Comment by jpommerening** [comment]
A wild API change appears!

The input control uses the i18n-service's `localizeRelaxed` method. (It's not very effective)

The control tries to call `localizeRelaxed` with a language tag which it gets by evaluating `$scope.i18n`. The API of the i18n service changed. It now handles language tag changes itself and only exposes `localize` and `format` methods that take messages directly, without the specification of a language tag.

The control needs to be changed to call `localize` without the language tag and use `whenLocaleChanged` to update the messages. We should also update Laxar's i18n service to use the global configuration if the widget has no `i18n` feature configuration so that controls like this work for widgets that don't implement i18n (LaxarJS/laxar#429). This should probably be enough to reestablish the previous behaviour. What's still missing is an API to "bind" an input to a custom i18n feature, so that the control uses `axI18n.forFeature( x ).localize` instead of `axI18n.localize`.

@x1B: did I get that right?

**Comment by x1B** [comment]
@jpommerening ![YES](https://s-media-cache-ak0.pinimg.com/originals/f8/09/07/f809070515b2489cf4297f81daf267e9.jpg)

**Comment by jpommerening** [comment]
feature branch pushed, need uikit update…

**Comment by jpommerening** [comment]
Implemented on `master` (`v3.0.0`)

Maintenance of 2.x continuing on `master-2.x`

## BREAKING CHANGE

The control has been updated to use Laxar 2 APIs and will no longer work with Laxar 1.x. In turn, _the artifact_ has been renamed to `laxar-input-control` (the Angular directive is still called `ax-input`).

It can be installed with `npm install laxar-input-control@^3` or `yarn add laxar-input-control@^3`.
Widgets can reference the control as `laxar-input-control` in their `widget.json`. Themes can style the control by providing a `laxar-input-control.css` file.

Despite the name change there should not be any changes in usage or behaviour.

**Comment by jpommerening** [comment]
(`v3.0.0-alpha.0` published to NPM)
